### ISSUE TITLE
Incompatible with mediator.js format.

### ISSUE THREAD

**Issue by Rojuinex** [echobnet/brokerjs#5]
It would be awesome if this was compatible with mediator.js so brokerjs can become a drop-in replacement for mediator.  For this to work the `options` parameter of the `subscribe`/`on` function  would need to follow the `callback function` parameter; and a `context` parameter would need to be tacked on the end so  the callback function can be ran in a specified context.  Like so:

`Broker#on(channelId, options, callbackOrsubId)` => `Broker#on(channelId, callbackOrsubId, options, context)`

Also options would need to also support `calls` and `predicate` keys.

`calls` allows the callback to be auto-unsubscribed after being called a certain number of times (really nice for one-off events).

and

`predicate` is a function that gets passed the args of `on`.  The callback function is only ran when `predicate` returns truty.  If it returns falsy the callback is not called (good for filtering secure messages and things).

**Comment by echobnet** [comment]
That make sense. Done and pretty much done. Please refer to the new 0.6.1 branch for changes.

- `options.count` was implemented
- `options.context` was implemented
- `broker.on` function arguments were changed

Predicate was not implemented yet and is a TBD feature (it'll probably come in later releases).
